### ISSUE TITLE
Does nxs file creation from xml work?

### ISSUE THREAD

**Issue by Ingvord** [pni-libraries/libpniio#123]
Hi,

I was playing with libpniio v1.3.1 trying to create files from xml templates and found out that resulting h5 file is empty - there is no structure in it.

When I do `make check` all tests are green, but when I directly run `./nexus_xml_create` I get the following:

```
root@a1bc328b2572:/libpniio/build/bin# ./nexus_xml_test 
Running 39 test cases...
/libpniio/test/nexus/xml/group_builder_test.cpp(71): error: in "NexusXMLTest/GroupBuilder/recursive_groups": unexpected exception thrown by xml_node = nexus::xml::Node::from_file("group_builder.xml")
/libpniio/test/nexus/xml/group_builder_test.cpp(75): error: in "NexusXMLTest/GroupBuilder/recursive_groups": check root_group.nodes.size() == 2 has failed
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140442980070848:
  #000: ../../../src/H5O.c line 120 in H5Oopen(): unable to open object
    major: Object header
    minor: Can't open object
  #001: ../../../src/H5Oint.c line 596 in H5O__open_name(): unable to open object
    major: Object header
    minor: Can't open object
  #002: ../../../src/H5Oint.c line 551 in H5O_open_name(): object not found
    major: Object header
    minor: Object not found
  #003: ../../../src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #004: ../../../src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: ../../../src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: ../../../src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'entry_1' doesn't exist
    major: Symbol table
    minor: Object not found
unknown location(0): fatal error: in "NexusXMLTest/GroupBuilder/recursive_groups": std::runtime_error: Failure open child node [entry_1]!
/libpniio/test/nexus/xml/group_builder_test.cpp(75): last checkpoint
unknown location(0): fatal error: in "NexusXMLTest/XMLNodeTest/CreationTest/test_from_file": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/node_test.cpp(53): last checkpoint: "test_from_file" test entry
unknown location(0): fatal error: in "NexusXMLTest/XMLNodeTest/InqueryTest/test_get_attribute": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/node_test.cpp(89): last checkpoint: "test_get_attribute" fixture ctor
unknown location(0): fatal error: in "NexusXMLTest/XMLNodeTest/InqueryTest/test_has_attribute": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/node_test.cpp(99): last checkpoint: "test_has_attribute" fixture ctor
unknown location(0): fatal error: in "NexusXMLTest/FieldBuilderTest/TestConstructionWithoutData/test_scalar_fields": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/field_builder_test.cpp(64): last checkpoint: "test_scalar_fields" fixture ctor
unknown location(0): fatal error: in "NexusXMLTest/FieldBuilderTest/TestConstructionWithoutData/test_multidim_fields": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/field_builder_test.cpp(148): last checkpoint: "test_multidim_fields" fixture ctor
unknown location(0): fatal error: in "DataspaceBuilderTest/test_case_1": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/dataspace_builder_test.cpp(39): last checkpoint: "test_case_1" test entry
unknown location(0): fatal error: in "DataspaceBuilderTest/test_case_2": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/dataspace_builder_test.cpp(48): last checkpoint: "test_case_2" test entry
unknown location(0): fatal error: in "DataspaceBuilderTest/test_case_3": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/dataspace_builder_test.cpp(54): last checkpoint: "test_case_3" test entry
unknown location(0): fatal error: in "DataspaceBuilderTest/test_case_4": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/dataspace_builder_test.cpp(60): last checkpoint: "test_case_4" test entry
unknown location(0): fatal error: in "DataspaceBuilderTest/test_case_5": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/dataspace_builder_test.cpp(66): last checkpoint: "test_case_5" test entry
unknown location(0): fatal error: in "DataspaceBuilderTest/test_case_6": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/dataspace_builder_test.cpp(72): last checkpoint: "test_case_6" test entry
unknown location(0): fatal error: in "AttributeBuilderTest/ScalarAttributesTest/test_uint8_attribute": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/scalar_attribute_builder_test.cpp(43): last checkpoint: "test_uint8_attribute" fixture ctor
unknown location(0): fatal error: in "AttributeBuilderTest/ScalarAttributesTest/test_int32_attribute": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/scalar_attribute_builder_test.cpp(57): last checkpoint: "test_int32_attribute" fixture ctor
unknown location(0): fatal error: in "AttributeBuilderTest/ScalarAttributesTest/test_string_attribute": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/scalar_attribute_builder_test.cpp(70): last checkpoint: "test_string_attribute" fixture ctor
unknown location(0): fatal error: in "AttributeBuilderTest/ArrayAttributesTest/test_uint8_attribute": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/array_attribute_builder_test.cpp(45): last checkpoint: "test_uint8_attribute" fixture ctor
unknown location(0): fatal error: in "AttributeBuilderTest/ArrayAttributesTest/test_int8_attribute": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/array_attribute_builder_test.cpp(63): last checkpoint: "test_int8_attribute" fixture ctor
unknown location(0): fatal error: in "AttributeBuilderTest/ArrayAttributesTest/test_string_attribute": pni::core::file_error: std::exception
/libpniio/test/nexus/xml/array_attribute_builder_test.cpp(79): last checkpoint: "test_string_attribute" fixture ctor
/libpniio/test/nexus/xml/create_test.cpp(48): error: in "CreateTest/from_simple_structure": unexpected exception thrown by xml::create_from_file(root_group,file)
unknown location(0): fatal error: in "CreateTest/from_simple_structure": std::runtime_error: No node [scan_1] below [/]!
/libpniio/test/nexus/xml/create_test.cpp(50): last checkpoint
/libpniio/test/nexus/xml/create_test.cpp(62): error: in "CreateTest/from_simple_structure_with_data": unexpected exception thrown by xml::create_from_file(root_group,file)
unknown location(0): fatal error: in "CreateTest/from_simple_structure_with_data": std::runtime_error: No node [scan_1] below [/]!
/libpniio/test/nexus/xml/create_test.cpp(62): last checkpoint
/libpniio/test/nexus/xml/create_test.cpp(73): error: in "CreateTest/from_detector_with_transformation": unexpected exception thrown by xml::create_from_file(root_group,file)
/libpniio/test/nexus/xml/create_test.cpp(85): error: in "CreateTest/detector_master_data_file": unexpected exception thrown by xml::create_from_file(data_file.root(),xml_data_file)
/libpniio/test/nexus/xml/create_test.cpp(86): error: in "CreateTest/detector_master_data_file": unexpected exception thrown by xml::create_from_file(master_file.root(),xml_master_file)

*** 27 failures are detected in the test module "Testing Nexus xml stack"
```

Also hdfview  shows no structure...

My client code looks like this:

```cpp
jlong Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_createFile(JNIEnv *env, jclass jClass, jstring jString,
                                                             jstring nxTemplate) {
    TRY
        NativeString nativeString(env, jString);
        NativeString nativeString1(env, nxTemplate);

        auto file = hdf5::file::create(nativeString.value,hdf5::file::AccessFlags::TRUNCATE);
        auto root_group = file.root();

        pni::io::nexus::xml::create_from_file(root_group, nativeString1.value);

        auto *rv = new NxFile(file);
        return reinterpret_cast<jlong>(rv);
    CATCH
}
```

Basically I pass two string args from my Java code: target file and xml template file and create a new h5 file. This gives me an empty file. 

XML template looks like this:

```xml
<group type="NXentry" name="entry">
    <group type="NXlog" name="string">
        <field type="string" name="value"/>
        <field type="uint64" name="time"/>
    </group>
    <group type="NXlog" name="double">
        <field type="float64" name="value"/>
        <field type="uint64" name="time"/>
    </group>
    <group type="NXlog" name="float">
        <field type="float32" name="value"/>
        <field type="uint64" name="time"/>
    </group>
    <group type="NXlog" name="long">
        <field type="int64" name="value"/>
        <field type="uint64" name="time"/>
    </group>
    <group type="NXlog" name="int">
        <field type="int32" name="value"/>
        <field type="uint64" name="time"/>
    </group>
    <group type="NXinstrument" name="instrument">
        <group type="NXdetector" name="detector">
            <field type="int16" name="data">
                <dimensions rank="3">
                    <dim value="0" index="1"/>
                    <dim value="8" index="2"/>
                    <dim value="4" index="3"/>
                </dimensions>
            </field>
        </group>
    </group>
    <group type="NXdata" name="data">
        <link target="/entry/instrument/detector/data" name="data"/>
    </group>
</group>
```

Code is executed in a docker container where all the libraries where built.

@jkotan could you please comment on this?

Thanks

**Comment by Ingvord** [comment]
Also with `h5dump`

```
root@a1bc328b2572:/libpniio/build/bin# h5dump CreateTest.nxs 
HDF5 "CreateTest.nxs" {
GROUP "/" {
}
}
```

**Comment by jkotan** [comment]
Hi Igor,

creating nexus from xml works and it is used on our beamlines in a few tango servers.
The tests work as well. But in order to run a separate test file you have to go `test/nexus/xml` directory and run the test
```
jkotan@haso228jk:~/sources/libpniio-build/test/nexus/xml$ ../../../bin/nexus_xml_test 
Running 39 test cases...

*** No errors detected
```
It is because in test you have a relative path to the xml files.

On which system do you try to run your example and have you try to make a simple test c++ example with your xml file without java?

Cheers,
Jan

**Comment by jkotan** [comment]
Igor, I've added a test in `issue_123` branch with your xml and it works OK.

**Comment by Ingvord** [comment]
@jkotan Cool! Thanks a lot!

That means there is some problem with the relative path to the template... I will double check that.

**Comment by Ingvord** [comment]
Nope... switching to absolute pathes did not change anything - there is still an empty h5 file is being created :(

**Comment by Ingvord** [comment]
I have added check to my jni code like this:

```cpp
        pni::io::nexus::xml::create_from_file(root_group, templatePath);
        if(get_node(root_group,"/entry").type() == Type::GROUP){
            jclass libpniioExceptionClass = env->FindClass("hzg/wpn/nexus/libpniio/jni/LibpniioException"); \
            env->ThrowNew(libpniioExceptionClass,"structure is not created");
        }
```

And I get an exception in Java:

```
hzg.wpn.nexus.libpniio.jni.LibpniioException: structure is not created

	at hzg.wpn.nexus.libpniio.jni.LibpniioJni.createFile(Native Method)
	at hzg.wpn.nexus.libpniio.jni.NxFile.create(NxFile.java:21)
	at hzg.wpn.nexus.libpniio.jni.TestCreateNexus.create(TestCreateNexus.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by jkotan** [comment]
In the tests the structure is created i.e.
```
jkotan@haso228jk:~/sources/libpniio-build/test/nexus/xml$ h5dump  CreateTest.nxs
HDF5 "CreateTest.nxs" {
GROUP "/" {
   GROUP "entry" {
      ATTRIBUTE "NX_class" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "NXentry"
         }
      }
      GROUP "data" {
         ATTRIBUTE "NX_class" {
            DATATYPE  H5T_STRING {
               STRSIZE H5T_VARIABLE;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            }
            DATASPACE  SCALAR
            DATA {
            (0): "NXdata"
            }
         }
         SOFTLINK "data" {
            LINKTARGET "/entry/instrument/detector/data"
         }
      }
      GROUP "double" {
         ATTRIBUTE "NX_class" {
            DATATYPE  H5T_STRING {
               STRSIZE H5T_VARIABLE;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            }
            DATASPACE  SCALAR
            DATA {
            (0): "NXlog"
            }
         }
         DATASET "time" {
            DATATYPE  H5T_STD_U64LE
            DATASPACE  SIMPLE { ( 0 ) / ( H5S_UNLIMITED ) }
            DATA {
            }
         }
         DATASET "value" {
            DATATYPE  H5T_IEEE_F64LE
            DATASPACE  SIMPLE { ( 0 ) / ( H5S_UNLIMITED ) }
            DATA {
            }
         }
      }
      GROUP "float" {
         ATTRIBUTE "NX_class" {
            DATATYPE  H5T_STRING {
               STRSIZE H5T_VARIABLE;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            }
            DATASPACE  SCALAR
            DATA {
            (0): "NXlog"
            }
         }
         DATASET "time" {
            DATATYPE  H5T_STD_U64LE
            DATASPACE  SIMPLE { ( 0 ) / ( H5S_UNLIMITED ) }
            DATA {
            }
         }
         DATASET "value" {
            DATATYPE  H5T_IEEE_F32LE
            DATASPACE  SIMPLE { ( 0 ) / ( H5S_UNLIMITED ) }
            DATA {
            }
         }
      }
      GROUP "instrument" {
         ATTRIBUTE "NX_class" {
            DATATYPE  H5T_STRING {
               STRSIZE H5T_VARIABLE;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            }
            DATASPACE  SCALAR
            DATA {
            (0): "NXinstrument"
            }
         }
         GROUP "detector" {
            ATTRIBUTE "NX_class" {
               DATATYPE  H5T_STRING {
                  STRSIZE H5T_VARIABLE;
                  STRPAD H5T_STR_NULLTERM;
                  CSET H5T_CSET_ASCII;
                  CTYPE H5T_C_S1;
               }
               DATASPACE  SCALAR
               DATA {
               (0): "NXdetector"
               }
            }
            DATASET "data" {
               DATATYPE  H5T_STD_I16LE
               DATASPACE  SIMPLE { ( 0, 8, 4 ) / ( H5S_UNLIMITED, 8, 4 ) }
               DATA {
               }
            }
         }
      }
      GROUP "int" {
         ATTRIBUTE "NX_class" {
            DATATYPE  H5T_STRING {
               STRSIZE H5T_VARIABLE;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            }
            DATASPACE  SCALAR
            DATA {
            (0): "NXlog"
            }
         }
         DATASET "time" {
            DATATYPE  H5T_STD_U64LE
            DATASPACE  SIMPLE { ( 0 ) / ( H5S_UNLIMITED ) }
            DATA {
            }
         }
         DATASET "value" {
            DATATYPE  H5T_STD_I32LE
            DATASPACE  SIMPLE { ( 0 ) / ( H5S_UNLIMITED ) }
            DATA {
            }
         }
      }
      GROUP "long" {
         ATTRIBUTE "NX_class" {
            DATATYPE  H5T_STRING {
               STRSIZE H5T_VARIABLE;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            }
            DATASPACE  SCALAR
            DATA {
            (0): "NXlog"
            }
         }
         DATASET "time" {
            DATATYPE  H5T_STD_U64LE
            DATASPACE  SIMPLE { ( 0 ) / ( H5S_UNLIMITED ) }
            DATA {
            }
         }
         DATASET "value" {
            DATATYPE  H5T_STD_I64LE
            DATASPACE  SIMPLE { ( 0 ) / ( H5S_UNLIMITED ) }
            DATA {
            }
         }
      }
      GROUP "string" {
         ATTRIBUTE "NX_class" {
            DATATYPE  H5T_STRING {
               STRSIZE H5T_VARIABLE;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            }
            DATASPACE  SCALAR
            DATA {
            (0): "NXlog"
            }
         }
         DATASET "time" {
            DATATYPE  H5T_STD_U64LE
            DATASPACE  SIMPLE { ( 0 ) / ( H5S_UNLIMITED ) }
            DATA {
            }
         }
         DATASET "value" {
            DATATYPE  H5T_STRING {
               STRSIZE H5T_VARIABLE;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            }
            DATASPACE  SCALAR
            DATA {
            (0): NULL
            }
         }
      }
   }
}
}
```
so it is some issue with your java wrapper.

**Comment by Ingvord** [comment]
UPD if statement was incorrect `==` instead of `!=`, damn copy-n-paste :)

Now there is no exception, but the resulting file is still empty...

**Comment by jkotan** [comment]
So the structure is in the memory but either it is in a different disk location you expect or it is not flushed to the disk by a proper close of the file.

**Comment by Ingvord** [comment]
I do close the file calling `close` on `hdf5::file::File` instance

**Comment by Ingvord** [comment]
Got it! Thanks to @jkotan 

I was using outdated `hdfview` (2.11) which is not able to browse the structure of the created file. `h5dump` and `silx` work nicely

Thanks
